# Generated by Django 4.0 on 2021-12-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='document',
            field=models.FileField(default='', upload_to='files'),
        ),
        migrations.AddField(
            model_name='orders',
            name='picture',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
